name: acme-mjpc
channels:
- defaults
- conda-forge
dependencies:
- python>=3.10,<3.11
- pip>=22.3.1
- conda>=23.3.1
- pip:
    - --find-links https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
    - -e ".[tf,jax,envs]"
